-- MySQL Script generated by MySQL Workbench
-- Sat Jun 18 09:46:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HomeCalander
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HomeCalander
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HomeCalander` DEFAULT CHARACTER SET utf8 ;
USE `HomeCalander` ;

-- -----------------------------------------------------
-- Table `HomeCalander`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HomeCalander`.`user` ;

CREATE TABLE IF NOT EXISTS `HomeCalander`.`user` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `username` VARCHAR(45) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `name_UNIQUE` (`username` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeCalander`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HomeCalander`.`type` ;

CREATE TABLE IF NOT EXISTS `HomeCalander`.`type` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `type` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HomeCalander`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HomeCalander`.`appointment` ;

CREATE TABLE IF NOT EXISTS `HomeCalander`.`appointment` (
                                                            `id` INT NOT NULL AUTO_INCREMENT,
                                                            `from` DATETIME NOT NULL,
                                                            `to` DATETIME NOT NULL,
                                                            `title` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    `user_id` INT NOT NULL,
    `type_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_appointment_user_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_appointment_type1_idx` (`type_id` ASC) VISIBLE,
    CONSTRAINT `fk_appointment_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `HomeCalander`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_appointment_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `HomeCalander`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
